---
- name: harden linux systems
  hosts: "{{ HOSTS | default('web') }}"
  become: true
  vars:
    - harden_firewall: false
    - harden_time: false
    - harden_selinux: false
    - harden_pci: false

  tasks:
    - name: Configure Firewall
      when: harden_firewall | bool
      include_role:
        name: linux-system-roles.firewall

    - name: Configure Timesync
      when: harden_time | bool
      include_role:
        name: linux-system-roles.timesync

    - name: selinux Hardening
      when: harden_selinux | bool
      include_role:
        name: linux-system-roles.selinux

    # run with --skip-tags accounts_passwords_pam_faillock_deny
    - name: Apply PCI Baseline
      when: harden_pci | bool
      include_role:
        name: redhatofficial.rhel8_pci_dss
